### ISSUE TITLE
Lack of `in-source: true` in bsconfig can cause asset resolution error

### ISSUE THREAD

**Issue by hew** [callstack/reroute-native#103]
In trying out this lib I found that, in order to get things working, I needed to add the following to my project's `bsconfig.js`:

```
  "package-specs": {
    "in-source": true
  },
```

This configuration setting in my project seems to take precedence over what is in `reroute-native`. That is, without it, all the compiled .js files end up in `lib/js/src`, in `reroute-native`, where they are trying to reference asset files that don't exist in that location.  

I find this a little confusing. I would expect libraries' `bsconfig.js` to take precedence here. Regardless, do we want to add some kind of note to this effect to the readme? I can open a PR, if so.

**Comment by wokalski** [comment]
cc @bobzhang. I think this is quite interesting considering what you're focused on now.

**Comment by knowbody** [comment]
@hew yes, please. I forgot to mention it in the README but I am aware that this is what is happening.

Let's see what @bobzhang comes back with 🙌

**Comment by knowbody** [comment]
@hew any update on this?

**Comment by hew** [comment]
@knowbody pr is up with those changes https://github.com/callstack/reroute-native/pull/107

**Comment by knowbody** [comment]
closed by #107
