### ISSUE TITLE
Semantics of StackNavigator

### ISSUE THREAD

**Issue by FiberJW** [callstack/reroute-native#74]
Thanks a lot for the hard work on this library!

I wanted to make you aware of an inconsistency between the StackNavigator and TabNavigator APIs. For the TabNavigator, the initial route you pass is to a prop named `initialRoute` which seems perfectly fine, but for StackNavigator, the prop with the same purpose is named `initialState`. I'm not sure if it was intentional to name it that or if it was a typo of sorts, but I feel that if it were renamed that it would be easier to remember between navigator types.

https://github.com/knowbody/reroute-native/blob/master/src/TabNavigator.re#L296
https://github.com/knowbody/reroute-native/blob/master/src/StackNavigator.re#L258

Thanks!

**Comment by knowbody** [comment]
closing in favour of #104
